/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_job_app_job_application_tracker_JNI_JNICPP */

#ifndef _Included_com_job_app_job_application_tracker_JNI_JNICPP
#define _Included_com_job_app_job_application_tracker_JNI_JNICPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_job_app_job_application_tracker_JNI_JNICPP
 * Method:    getTestNativeString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_job_1app_job_1application_1tracker_JNI_JNICPP_getTestNativeString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
